version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  api:
    build: .
    container_name: tvpl_ai_api
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./output:/app/output
      - ./requirements.txt:/app/requirements.txt:ro

    env_file:
      - .env 
      
    environment:
      - QDRANT_HOST=localhost
      - QDRANT_PORT=6333

volumes:
  qdrant_storage:
